image_root: '/home/ubuntu/lxd-workplace/LYT/FFLIP/CelebA/images'
ann_root: '/home/ubuntu/lxd-workplace/LYT/FFLIP/CelebA/dialog'
dataset: 'celebadialog'

pretrained: '/home/ubuntu/lxd-workplace/LYT/FFLIP/itc_itm_mm/outputs/pretrain-base/checkpoint_best.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size_train: 64
batch_size_test: 64

queue_size: 61440
alpha: 0.4
k_test: 32

# optimizer
weight_decay: 0.05
init_lr: 3e-3
min_lr: 0
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 500